site_name: "ROADMAPPERS"
repo_name: Roadmappers.ru
repo_url: https://github.com/halltape/HalltapeRoadmapDE
site_url: https://roadmappers.ru
copyright: MIT

# Явное, лаконичное меню
nav:
  - В начало: page/docs/README.md

theme:
  name: material
  palette:
    scheme: slate  # тёмная тема (можно убрать для светлой)
  font:
    text: Roboto
    code: Fira Mono
  code:
    highlight_theme: dracula
  logo: _frontend/images/logo.svg

# Только свой CSS
extra_css:
  - _frontend/css/custom.css

extra_javascript:
  - _frontend/js/toc-home.js
  - _frontend/js/scroll-to-top.js


markdown_extensions:
  - admonition
  - codehilite
  - tables
  - footnotes